services:
  vzlogger:
    container_name: vzlogger
    image: vzlogger:latest
    volumes:
      - ./vzlogger.conf:/etc/vzlogger.conf:ro
      - ./logs:/var/log/vzlogger
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "8081:8081"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: always
