services:
  influxdb:
    image: influxdb:2.7.10-alpine
    env_file:
      - influxv2.env
    volumes:
      - influxdbv2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:1.32.2-alpine
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - influxv2.env

volumes:
  influxdbv2:
