services:
  influxdb_dev:
    image: influxdb:2.7.10-alpine
    env_file:
      - influxv2.env
    volumes:
      - influxdbv2_dev:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  telegraf_dev:
    image: telegraf:1.32.2-alpine
    depends_on:
      - influxdb_dev
    volumes:
      - ./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./input.json:/var/tmp/input.json
    env_file:
      - influxv2.env

volumes:
  influxdbv2_dev:
