services:
  inverter-bridge:
    container_name: inverter-bridge
    build:
      context: ./inverter-bridge
    env_file: # specifies the USER_ID, REMOTE_SERVER_URL and INVERTER_ADDRESS, so docker compose can be published
      - .env
    environment:
      - INTERVAL=60000
    restart: unless-stopped
